// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJDbR9b045y5omjir9eHPjE02mdcia-mA',
    appId: '1:604592517680:web:cb3b644d2dd8d21eba73f5',
    messagingSenderId: '604592517680',
    projectId: 'tsecapp-43564',
    authDomain: 'tsecapp-43564.firebaseapp.com',
    storageBucket: 'tsecapp-43564.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXNlW8rJi-IeCT9sLJJBbP8vf88CHZy0g',
    appId: '1:604592517680:android:86a11d8ba28e7eceba73f5',
    messagingSenderId: '604592517680',
    projectId: 'tsecapp-43564',
    storageBucket: 'tsecapp-43564.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9HkUY3q8oeD67F6sn5kyKGnHLh_E94TU',
    appId: '1:604592517680:ios:4b442914a811bed5ba73f5',
    messagingSenderId: '604592517680',
    projectId: 'tsecapp-43564',
    storageBucket: 'tsecapp-43564.appspot.com',
    iosClientId: '604592517680-2v1916a08ot6e68mi2bltt2s7mpo2s22.apps.googleusercontent.com',
    iosBundleId: 'com.example.tsecApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9HkUY3q8oeD67F6sn5kyKGnHLh_E94TU',
    appId: '1:604592517680:ios:4b442914a811bed5ba73f5',
    messagingSenderId: '604592517680',
    projectId: 'tsecapp-43564',
    storageBucket: 'tsecapp-43564.appspot.com',
    iosClientId: '604592517680-2v1916a08ot6e68mi2bltt2s7mpo2s22.apps.googleusercontent.com',
    iosBundleId: 'com.example.tsecApp',
  );
}
